### ISSUE TITLE
Error downloading browsers

### ISSUE THREAD

**Issue by SupremeTechnopriest** [GoogleChromeLabs/selenium-assistant#114]
Hello, came across this error yesterday.  Everything was working fine the day before.  Maybe the latest version introduced a bug?  Here's the output:

```[Edgemesh]: Downloading browsers......
internal/errors.js:251
  const [ code, uvmsg ] = errmap.get(ctx.errno);
                                 ^

TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:113:24)
    at Object.copyFileSync (fs.js:1724:3)
    at copyFile (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:78:8)
    at onFile (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:58:12)
    at getStats (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:39)
    at startCopy (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:41:10)
    at fs.readdirSync.forEach.item (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:142:5)
    at Array.forEach (<anonymous>)
    at copyDir (/Users/rl/Sites/edgemesh/core/browser/node_modules/selenium-assistant/node_modules/fs-extra/lib/copy-sync/copy-sync.js:141:23)```

**Comment by mklnz** [comment]
I have the same issue, any luck with fixing it?

**Comment by mormeir** [comment]
Same for me.. any suggestions?
